
version: 2

models:
  - name: films
    description: "This table contains details about film."
    columns:
      - name: film_id
        description: "Unique identifier for the film."
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the film."
        tests:
          - not_null
      - name: release_date
        description: "Relase date of the film."
        tests:
          - not_null
      - name: price
        description: "The ticket price of the film."
        tests:
          - not_null
      - name: rating
        description: "The MPAA rating of the film."
        tests:
          - not_null
      - name: user_rating
        description: "The user rating for the film."
        tests:
          - not_null
        
  - name: actors
    description: "This table contain details about actors."
    columns:
      - name: actor_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: name
        description: "First name of the actor."
        tests:

  - name: film_actors
    description: "This table contain details about actors."
    columns:
      - name: film_id
        description: "Identifier for the film"
        tests:
          - not_null
      - name: actor_id
        description: "Identifier for the actor."
        tests:
          - not_null

  - name: film_ratings
    description: "This model aggregates film data and calculates the average rating for each film."
    columns:
      - name: film_id
        description: "Identifier for the film"
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the film."
        tests:
          - not_null
      - name: release_date
        description: "Relase date of the film."
        tests:
          - not_null
      - name: price
        description: "The ticket price of the film."
        tests:
          - not_null
      - name: rating
        description: "The MPAA rating of the film."

      - name: user_rating
        description: "The user rating for the film."
        tests:
          - not_null
      - name: actor_count
        description: "THe number of actors in the file."
        tests:
          - not_null
      - name: avg_actor_rating
        description: "THe average rating of film that the actors of this film have acted in."
        tests:
          - not_null
